### ISSUE TITLE
X axis can not be ordered 

### ISSUE THREAD

**Issue by marko0105** [zBritva/charticulator-visual-community#32] opened 2024-09-15 14:53 UTC
Hi,
x axis categories on waterfall chart can not be ordered by using another column.
Column is set as integer, and it hasn't been recognized to sort it.
I have also tried and added string column, no success as well - it doesn't order the labels.
If I do custom ordering, it is ok only for current set up, but of I change value on the slicer then order resets - as it was before ordering adjustment.
![Screenshot 2024-09-15 164601](https://github.com/user-attachments/assets/68f05a30-4940-4a98-9ef0-2bb4d5f0e21a)

**Comment by zBritva** [comment] 2024-09-16 20:44
@marko0105 yes, it's known issue. The app uses standart sort function of JS, that sorts numbers as string.

**Comment by marko0105** [comment] 2024-09-17 08:17
@zBritva , thanks for reply. I tried to replace sort column with letters and it still didn't work. It didn't sort letters in alphabetical order.

**Comment by zBritva** [comment] 2024-09-17 18:17
@marko0105 Thanks! I will check the issue.

**Comment by zBritva** [comment] 2024-09-17 18:26
Could you confirm the behaviour?
After selecting the column for sorting, we need to click on "Sort" order to sort axis data properly:
![sorting-axis](https://github.com/user-attachments/assets/10d894db-062c-4948-9d3f-1380c0f67510)

Thanks!

**Comment by marko0105** [comment] 2024-09-17 18:33
Hi, still not working on my end.
![Screenshot 2024-09-17 203037](https://github.com/user-attachments/assets/c5c9c173-131a-42e8-b187-4c3546707c13)

**Comment by marko0105** [comment] 2024-09-17 18:37
Hi,
to elaborate a little bit, column type_sort I don't show on the waterfall chart, it has been used only for sorting type_label.
type_sort column is in the model, in the charticulator.

**Comment by zBritva** [comment] 2024-09-17 18:49
@marko0105 I have preproduced the issue:

![image](https://github.com/user-attachments/assets/709e81b3-7f25-4675-bc96-712f2907f83d)

Thanks! Confirm that issue is "standart sort function of JS"
I will update to provide custom sort for numers and dates in the next version of the visual.

**Comment by marko0105** [comment] 2024-09-19 08:21
@zBritva , thanks a lot. 
Do you have by any chances when next version of the visual will be available?

Thank you.

**Comment by zBritva** [comment] 2024-09-19 23:23
@marko0105 ~2-3 weeks.

You can get DEV version as workaround on https://ilfat-galiev.im/

![image](https://github.com/user-attachments/assets/ef5cd8c6-a47d-4d30-8d84-c25c82b85f89)
Ensure that the fix works for you

**Comment by marko0105** [comment] 2024-09-26 08:10
@zBritva , I am using DEV version, sorting seems to work now. Another issue pops up, after click on Save it returns sorting column to type_label column for sorting instead of keeping type_sort column.
![OrderSort](https://github.com/user-attachments/assets/1ed8fe65-2d39-4b8e-b8ab-d8d5c13ca951)
![OrderSort_1](https://github.com/user-attachments/assets/3502a843-c64b-4cdd-9016-3465ec0f5ea6)

**Comment by marko0105** [comment] 2024-09-26 08:11
Order by was type_sort which is ok, and it is sorting correctly, but when pressing the 
![image](https://github.com/user-attachments/assets/47d92410-7b96-47bd-8d79-80bdaa603554)
it swaps type_sort to type_label Order by

**Comment by marko0105** [comment] 2024-10-03 06:16
@zBritva , Hi, any progress on Order by issue? I am using DEV, as you suggested, and just checked - Order by is changing field for ordering when you Save the chart.
Thank you.
Br

**Comment by zBritva** [comment] 2024-10-03 17:51
@marko0105 unfortunately there is another bug, fix of that will include to next version:

https://ilfat-galiev.im/docs/charticulator/changelog#1300-next-version

**Comment by zBritva** [comment] 2024-10-03 17:58
As workaround, you can use https://appsource.microsoft.com/en-us/product/power-bi-visuals/ilfatgaliev1696579877540.editorvisual?tab=Overview to edit charticulator schema:

Switch the visual on the report to "Power BI visual editor" and switch settings to Chartiuclator:

![image](https://github.com/user-attachments/assets/9096bc49-cd4d-482a-98bb-7d6e48f846c3)

The visual will load the schema:

![image](https://github.com/user-attachments/assets/643679c7-3843-4a13-90fe-e298fe35aff4)

Format the JSON by context menu and find: "orderByExpression":

![image](https://github.com/user-attachments/assets/aee82d4c-7a6c-492a-a799-38c0b9c5c9f3)

Change column name to another column.

Save the changes and switch the visual back to Charticulator instance

**Comment by marko0105** [comment] 2024-10-03 20:25
@zBritva, thank you so much - workaround is working.
much appreciated.
Br

**Comment by zBritva** [comment] 2024-11-24 03:50
The issue is fixed in [1.3.0.0](https://ilfat-galiev.im/docs/charticulator/changelog#1300) version

**Closed by zBritva** 2024-11-24 03:50 UTC
Labels: bug, enhancement
